#!/bin/sh

# Starts and stops daemons installed in /opt

. /etc/init.d/functions

check_zpkg_disable()
{
    grep -q '^NO_ZPKG' $(cat /tmp/config_file)
}

do_start()
{
    loaded=0
    failed=0
    if check_zpkg_disable; then
        echo ZPKG startup disabled
    else
        for script in /opt/etc/rc.d/S*; do
            if [ -x $script ]; then
                loaded=$((loaded + 1))
                $script start  ||  failed=$((failed + 1))
            fi
        done
    fi

    if [ $loaded = 0 ]; then
        # If no zpkg files found then report attention needed
        set-led ATTENTION
    elif [ $failed -gt 0 ]; then
        set-led ZPKG_ERR
    else
        set-led SYSTEM_OK
    fi
}

do_stop()
{
    set-led ATTENTION
    for script in /opt/etc/rc.d/K*; do
        [ -x $script ]  &&  $script stop
    done
}

do_start_stop "$1" zpkg
