REQUIRED_SYMBOLS += BOOTGEN

# The first stage bootloader image is managed here under source control, despite
# being a binary, because it will never change and is build as part of the
# Xilinx build process.
FSBL_ELF = $(PWD)/boot/fsbl.elf

ifdef SDK_ROOT
    BOOTGEN ?= $(SDK_ROOT)/bin/bootgen
endif

DEVICE_TREE_DTB = $(BOOT_BUILD)/devicetree.dtb

BOOT_FILES += $(BOOT_BUILD)/boot.bin    # Second stage bootloader
BOOT_FILES += $(DEVICE_TREE_DTB)        # Device tree for kernel

