on:
  workflow_call:


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-rootfs

      - name: Checkout rootfs builder
        uses: actions/checkout@v2
        with:
          repository: dls-controls/rootfs
          path: rootfs
       
      - name: Checkout annotypes
        uses: actions/checkout@v2
        with:
          repository: dls-controls/annotypes
          path: annotypes
        
      - name: Checkout pymalcolm
        uses: actions/checkout@v2
        with:
          repository: dls-controls/pymalcolm
          path: pymalcolm

      - name: Checkout malcolmjs
        uses: actions/checkout@v2
        with:
          repository: dls-controls/malcolmjs
          path: malcolmjs

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Docker Buildx 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Build and push container image to registry
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: . 
          file: ./PandABlocks-rootfs/Dockerfile
          push: false 
          tags: pandablocks-dev-container:latest
          outputs: type=docker, dest=./pandablocks-dev-container.tar
          cache-to: type=gha      

      # Upload container as an artifact 
      - name: Upload contianer as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: pandablocks-dev-container
          path: .
