name: Code CI

on:
  push:
    branches:
      - 'containers-tizayi'
  pull_request:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-rootfs

      - name: Checkout rootfs builder
        uses: actions/checkout@v2
        with:
          repository: dls-controls/rootfs
          path: rootfs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Build and push container image to registry
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: . 
          file: ./PandABlocks-rootfs/Dockerfile
          push: false 
          tags: pandablocks:latest
          outputs: type=docker, dest=/tmp/pandablocks.tar
      
      # Upload container as an artifact 
      - name: Upload contianer as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: pandablocks
          path: /tmp
  
  build:
    needs: [build-image]
    strategy:
      fail-fast: false
      matrix:
        platform: ["zynq", "zynqmp"]

    name: build/${{ matrix.platform }}
    runs-on: ubuntu-latest

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Download artifact of image
      - uses: actions/download-artifact@v2
        with:
          name: pandablocks
          path: /tmp

      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-rootfs
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      # Build
      - name: Make zips
        run: |
          cd /tmp
          docker load --input pandablocks.tar
          cd ${{ github.workspace }}
          docker run -it --security-opt label=disable \
            -v "${{ github.workspace }}:/repos" \
            -v "${{ github.workspace }}/build:/build:Z,U" \
            pandablocks:latest \
            /bin/bash -c \
            "cd PandABlocks-rootfs && make zips"

      # Artifacts
      - name: Upload deps and boot build files
        uses: actions/upload-artifact@v2
        with:
          name: zips
          path: build/*.zip

  release:
    needs: [build]
    runs-on: ubuntu-latest
    # make a release on every tag
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: zips
          path: zips

      - name: Github Release
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: softprops/action-gh-release@2d72d869af3bf23602f9593a1e3fd739b80ac1eb  # v0.1.12
        with:
          files: zips/*
          body: See [Changelog](CHANGELOG.rst) for more details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
