name: Code CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["zynq", "zynqmp"]

    name: build/${{ matrix.platform }}
    runs-on: ubuntu-latest

    steps:

      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-rootfs
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      - name: Checkout rootfs builder
        uses: actions/checkout@v2
        with:
          repository: dls-controls/rootfs
          path: rootfs

      # ARM GNU Toolchain
      - name: Download Arm GNU toolchain
        run: bash PandABlocks-rootfs/.github/scripts/GNU-toolchain.sh ${{ matrix.platform }}

      # Tar dependancies
      - name: Download tar file dependencies
        run: bash PandABlocks-rootfs/.github/scripts/tar-files.sh

      # System dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libncurses5-dev expat
          sudo pip install rst2pdf

      # CONFIG files
      - name: Generate CONFIG files
        run: |
          bash PandABlocks-rootfs/.github/scripts/config-file-pbrootfs.sh ${{ matrix.platform }}
          bash PandABlocks-rootfs/.github/scripts/config-file-rootfs.sh

      # Build
      - name: Make zips
        run: |
          cd PandABlocks-rootfs
          make zips

      # Artifacts
      - name: Upload deps and boot build files
        uses: actions/upload-artifact@v2
        with:
          name: zips
          path: build/*.zip

  release:
    needs: [build]
    runs-on: ubuntu-latest
    # make a release on every tag
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: zips
          path: zips

      - name: Github Release
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: softprops/action-gh-release@2d72d869af3bf23602f9593a1e3fd739b80ac1eb  # v0.1.12
        with:
          files: zips/*
          body: See [Changelog](CHANGELOG.rst) for more details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
