name: Docs CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-rootfs
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      # System dependencies (required for build)
      - name: Install system dependencies
        run: |
          sudo pip install rst2pdf sphinx sphinx-rtd-theme --upgrade docutils==0.16

      # CONFIG files
      - name: Generate CONFIG files - zynq
        run: |
          sudo bash PandABlocks-rootfs/.github/scripts/config-file-pbrootfs.sh zynq

      # Build
      - name: Build Docs
        run: |
          cd PandABlocks-rootfs
          make docs

      - uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: ${{ github.ref }}
          split-by: /

      # Publish docs
      - name: Move to versioned directory
        # e.g. master or 0.1.2
        run: |
          mkdir PandABlocks-rootfs/.github/pages
          mv build/build/html "PandABlocks-rootfs/.github/pages/${{ steps.split.outputs._2 }}"

      - name: Publish Docs to gh-pages
        # Only master and tags are published
        if: "${{ github.repository_owner == 'PandABlocks' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')) }}"
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: PandABlocks-rootfs/.github/pages
          keep_files: true
