name: Docs CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-rootfs
          # require history to get back to last tag for version number of branches
          fetch-depth: 0
      
      # pull image from ghcr and build docs in container 
      - name: pull image and build docs 
        run: |
          docker pull ghcr.io/pandablocks/pandablocks-dev-container:latest
          docker run \
            -v "${{ github.workspace }}:/repos" \
            -v "${{ github.workspace }}/build:/build" \
            ghcr.io/pandablocks/pandablocks-dev-container:latest \
            /bin/bash -c \
            "cd PandABlocks-rootfs && make docs"

      - uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: ${{ github.ref }}
          split-by: /

      # Publish docs
      - name: Move to versioned directory
        # e.g. master or 0.1.2
        run: mv build/build/html "PandABlocks-rootfs/.github/pages/${{ steps.split.outputs._2 }}"

      - name: Publish Docs to gh-pages
        # Only master and tags are published
        if: "${{ github.repository_owner == 'PandABlocks' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')) }}"
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: PandABlocks-rootfs/.github/pages
          keep_files: true
