name: Make Zips CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: ["zynq", "zynqmp"]

    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-rootfs
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      - name: Checkout rootfs builder
        uses: actions/checkout@v2
        with:
          repository: dls-controls/rootfs
          path: rootfs

      # ARM GNU Toolchain
      - name: Download Arm GNU toolchain - ${{ matrix.platform }}
        run: bash PandABlocks-rootfs/.github/scripts/GNU-toolchain.sh ${{ matrix.platform }}

      # Tar dependancies
      - name: Download tar file dependencies
        run: bash PandABlocks-rootfs/.github/scripts/tar-files.sh

      # System dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libncurses5-dev expat
          sudo pip install rst2pdf

      #CONFIG files
      - name: Generate CONFIG files - ${{ matrix.platform }}
        run: |
          bash PandABlocks-rootfs/.github/scripts/config-file-pbrootfs.sh ${{ matrix.platform }}
          bash PandABlocks-rootfs/.github/scripts/config-file-rootfs.sh

      # Verification of files/file structure
      - name: List workspace files
        run: |
          ls ${{ github.workspace }}
          echo " "
          ls PandABlocks-rootfs
          echo " "
          ls rootfs
          echo " "
          ls tar-files
          echo " "
          cat PandABlocks-rootfs/CONFIG
      #    echo " "
      #    cat rootfs/CONFIG.local

      # Build
      - name: Make zips
        run: |
          cd PandABlocks-rootfs
          make zips

      # Verification of build files
      #- name: List build files
      #  run: ls build

      # Artifacts
      - name: Upload deps and boot build files
        uses: actions/upload-artifact@v2
        with:
          name: deps&boot-${{ matrix.platform }}
          path: |
            build/deps-*.zip
            build/boot-*.zip
  
  release:
    needs: [build]
    runs-on: ubuntu-latest
    # make a release on every tag
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: |
            deps&boot-zynq
            deps&boot-zynqmp
          path:
            artifacts 

      - name: Github Release
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: softprops/action-gh-release@2d72d869af3bf23602f9593a1e3fd739b80ac1eb  # v0.1.12
        with:
          files: artifacts/*
          body: See [Changelog](CHANGELOG.rst) for more details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
