name: Make Zips CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # TODO: add following steps:  

      # - Checkout PandABlocks-rootfs repo (This)

      # - Install dependencies:
      #   - Xilinx U-boot & Linux kernel sources
      #   - rootfs buider
      #   - tar files
      #   - ARM GNU cross compiler tool chain (AND EXTRACT)

      # - Create and fill out CONFIG files:
      #   - PandABlocks-rootfs repo (This)
      #   - rootfs builder repo

      # - Run make zips command

      # - Store artifacts DEPS.zip and BOOT.zip 

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Checkout rootfs builder
        uses: actions/checkout@v2
        with:
          repository: dls-controls/rootfs

      #Temporary verification
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

