name: Make Zips CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: ["zynq", "zynqmp"]

    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: pandABlocks-rootfs

      - name: Checkout rootfs builder
        uses: actions/checkout@v2
        with:
          repository: dls-controls/rootfs
          path: rootfs

      # ARM GNU Toolchain
      - name: Download Arm GNU toolchain - ${{ matrix.platform }}
        run: sudo bash pandABlocks-rootfs/.github/scripts/GNU-toolchain.sh ${{ matrix.platform }}
        shell: bash

      # Tar dependancies
      - name: Download tar file dependencies
        run: sudo bash pandABlocks-rootfs/.github/scripts/tar-files.sh
        shell: bash

      # System dependencies (required for build)
      - name: Install system dependencies
        run: |
          sudo apt-get install -y gcc make autoconf automake libffi-dev libtool fakeroot libreadline6-dev libncurses5 libncurses5-dev expat libexpat1-dev zlib1g-dev libssl-dev
          sudo pip install rst2pdf

      #CONFIG files
      - name: Generate CONFIG files - ${{ matrix.platform }}
        run: |
          mkdir build
          sudo bash pandABlocks-rootfs/.github/scripts/config-files.sh ${{ matrix.platform }}
        shell: bash

      # Verification of files/file structure
      - name: List workspace files
        run: |
          ls ${{ github.workspace }}
          echo " "
          ls ${{ github.workspace }}/pandABlocks-rootfs
          echo " "
          ls ${{ github.workspace }}/rootfs
          echo " "
          ls ${{ github.workspace }}/tar-files
          echo " "

      # Build
      - name: Make zips
        run: |
          cd pandABlocks-rootfs
          make zips

      # Verification of build files
      - name: List build files
        run: ls ${{ github.workspace }}/build

      # Artifacts
      - name: Upload deps and boot build files
        uses: actions/upload-artifact@v2
        with:
          name: build-files-${{ matrix.platform }}
          path: |
            ${{ github.workspace }}/build/deps-*.zip
            ${{ github.workspace }}/build/boot-*.zip
        

