name: Make Zips CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_LOCATION: /home/runner/work/PandABlocks-rootfs
    steps:
      # TODO: add following steps:  

      # - Checkout PandABlocks-rootfs repo (This)

      # - Install dependencies:
      #   - Xilinx U-boot & Linux kernel sources
      #   - rootfs buider
      #   - tar files
      #   - ARM GNU tool chain (AND EXTRACT)

      # - Create and fill out CONFIG files:
      #   - PandABlocks-rootfs repo (This)
      #   - rootfs builder repo

      # - Run make zips command

      # - Store artifacts DEPS.zip and BOOT.zip 

      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: pandABlocks-rootfs

      - name: Checkout rootfs builder
        uses: actions/checkout@v2
        with:
          repository: dls-controls/rootfs
          path: rootfs
          
      - name: Download Arm GNU toolchain - PLATFORM = zynq
        uses: wei/wget@v1
        with:
          args: -O arm-gcc.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf.tar.xz

      - name: Extract Arm GNU toolchain - PLATFORM = zynq
        run: |
          tar -xf arm-gcc.tar.xz
          rm arm-gcc.tar.xz

      #Temporary verification
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          ls ${{ github.workspace }}/pandABlocks-rootfs
          ls ${{ github.workspace }}/rootfs
      - run: echo "🍏 This job's status is ${{ job.status }}."

