name: Make Zips CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: ["zynq", "zynqmp"]

    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-rootfs

      - name: Checkout rootfs builder
        uses: actions/checkout@v2
        with:
          repository: dls-controls/rootfs
          path: rootfs

      # ARM GNU Toolchain
      - name: Download Arm GNU toolchain - ${{ matrix.platform }}
        run: sudo bash PandABlocks-rootfs/.github/scripts/GNU-toolchain.sh ${{ matrix.platform }}

      # Tar dependancies
      - name: Download tar file dependencies
        run: sudo bash PandABlocks-rootfs/.github/scripts/tar-files.sh

      # System dependencies (required for build)
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libncurses5-dev expat
          sudo pip install rst2pdf

      #CONFIG files
      - name: Generate CONFIG files - ${{ matrix.platform }}
        run: |
          mkdir build
          sudo bash PandABlocks-rootfs/.github/scripts/config-file-rootfs.sh ${{ matrix.platform }}

      # Verification of files/file structure
      #- name: List workspace files
      #  run: |
      #    ls ${{ github.workspace }}
      #    echo " "
      #    ls pandABlocks-rootfs
      #    echo " "
      #    ls rootfs
      #    echo " "
      #    ls tar-files
      #    echo " "

      # Build
      - name: Make zips
        run: |
          cd PandABlocks-rootfs
          make zips

      # Verification of build files
      #- name: List build files
      #  run: ls build

      # Artifacts
      - name: Upload deps and boot build files
        uses: actions/upload-artifact@v2
        with:
          name: build-files-${{ matrix.platform }}
          path: |
            build/deps-*.zip
            build/boot-*.zip

      # Release 
      - name: Release
        uses: softprops/action-gh-release@v1
        # Only release when a tag is pushed
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/deps-*.zip
            build/boot-*.zip
          body_path: ${{ github.workflow }}/PandABlocks-rootfs/CHANGELOG.rst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
